// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManager.database;

#nullable disable

namespace MovieManager.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220926195718_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieManager.database.Movie", b =>
                {
                    b.Property<string>("movieCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("movie_code");

                    b.HasKey("movieCode");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieManager.database.RankingData", b =>
                {
                    b.Property<int>("rankNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rank_no");

                    b.HasKey("rankNo");

                    b.ToTable("RankingData");
                });
#pragma warning restore 612, 618
        }
    }
}
