// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManager.database;

#nullable disable

namespace MovieManager.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieManager.database.DailyBoxOffice", b =>
                {
                    b.Property<int>("rankNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rank_no");

                    b.HasKey("rankNo");

                    b.ToTable("daily_box_office");
                });

            modelBuilder.Entity("MovieManager.database.Movie", b =>
                {
                    b.Property<string>("movieCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("movie_code");

                    b.HasKey("movieCode");

                    b.ToTable("movie");
                });

            modelBuilder.Entity("MovieManager.database.WeeklyBoxOffice", b =>
                {
                    b.Property<int>("rankNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rank_no");

                    b.HasKey("rankNo");

                    b.ToTable("weekly_box_office");
                });
#pragma warning restore 612, 618
        }
    }
}
